unit Proxy.Readers;

interface

// Generated by Proxy Generator for FireDAC at 2019-09-08 23:49
uses
  System.Variants,
  Data.DB,
  Data.DataProxy,
  System.SysUtils,
  System.Classes,
  FireDAC.Comp.Client;

type
  TReaderProxy = class(TDatasetProxy)
  private
    FReaderId: TIntegerField;
    FFirstName: TWideStringField;
    FLastName: TWideStringField;
    FEmail: TWideStringField;
    FCompany: TWideStringField;
    FBooksRead: TIntegerField;
    FLastReport: TDateTimeField;
    FCreated: TDateTimeField;
  protected
    procedure ConnectFields; override;
  public
    class function CreateMockTable(AOwner: TComponent): TFDMemTable;
    // ---
    function generateNewUniqueID: integer;
    function LoacateReaderIdByEmil(const email: string): Variant;
    // ---
    property ReaderId: TIntegerField read FReaderId;
    property FirstName: TWideStringField read FFirstName;
    property LastName: TWideStringField read FLastName;
    property email: TWideStringField read FEmail;
    property Company: TWideStringField read FCompany;
    property BooksRead: TIntegerField read FBooksRead;
    property LastReport: TDateTimeField read FLastReport;
    property Created: TDateTimeField read FCreated;
  end;

implementation

procedure TReaderProxy.ConnectFields;
const
  ExpectedFieldCount = 8;
begin
  FReaderId := FDataSet.FieldByName('ReaderId') as TIntegerField;
  FFirstName := FDataSet.FieldByName('FirstName') as TWideStringField;
  FLastName := FDataSet.FieldByName('LastName') as TWideStringField;
  FEmail := FDataSet.FieldByName('Email') as TWideStringField;
  FCompany := FDataSet.FieldByName('Company') as TWideStringField;
  FBooksRead := FDataSet.FieldByName('BooksRead') as TIntegerField;
  FLastReport := FDataSet.FieldByName('LastReport') as TDateTimeField;
  FCreated := FDataSet.FieldByName('Created') as TDateTimeField;
  Assert(FDataSet.Fields.Count = ExpectedFieldCount);
end;

class function TReaderProxy.CreateMockTable(AOwner: TComponent): TFDMemTable;
var
  ds: TFDMemTable;
begin
  ds := TFDMemTable.Create(AOwner);
  with ds do
  begin
    FieldDefs.Add('ReaderId', ftInteger);
    FieldDefs.Add('FirstName', ftWideString, 100);
    FieldDefs.Add('LastName', ftWideString, 100);
    FieldDefs.Add('Email', ftWideString, 50);
    FieldDefs.Add('Company', ftWideString, 100);
    FieldDefs.Add('BooksRead', ftInteger);
    FieldDefs.Add('LastReport', ftDateTime);
    FieldDefs.Add('Created', ftDateTime);
    CreateDataSet;
  end;
{$REGION 'Append data to MemTable: Readers'}
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 1;
    FieldByName('FirstName').Value := 'Routledge';
    FieldByName('LastName').Value := 'Ned';
    FieldByName('Email').Value := 'nroutledge2j@europa.eu';
    FieldByName('Company').Value := 'Stamm, Cassin and Bins';
    FieldByName('BooksRead').Value := 1;
    FieldByName('LastReport').Value := EncodeDate(2018, 4, 10);
    FieldByName('Created').Value := EncodeDate(2017, 9, 15);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 2;
    FieldByName('FirstName').Value := 'Millan';
    FieldByName('LastName').Value := 'Marcus';
    FieldByName('Email').Value := 'mmillan12@prlog.org';
    FieldByName('Company').Value := '';
    FieldByName('BooksRead').Value := 2;
    FieldByName('LastReport').Value := EncodeDate(2018, 6, 3);
    FieldByName('Created').Value := EncodeDate(2017, 10, 27);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 3;
    FieldByName('FirstName').Value := 'Sobieraj';
    FieldByName('LastName').Value := 'Stanis³aw';
    FieldByName('Email').Value := 'staszek.sobieraj@empik.com';
    FieldByName('Company').Value := 'Empik sp. z o.o.';
    FieldByName('BooksRead').Value := 1;
    FieldByName('LastReport').Value := EncodeDate(2018, 6, 10);
    FieldByName('Created').Value := EncodeDate(2017, 11, 23);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 4;
    FieldByName('FirstName').Value := 'Cogdell';
    FieldByName('LastName').Value := 'Torbjörn';
    FieldByName('Email').Value := 'tcogdell2j@patch.com';
    FieldByName('Company').Value := '';
    FieldByName('BooksRead').Value := 2;
    FieldByName('LastReport').Value := EncodeDate(2018, 7, 21);
    FieldByName('Created').Value := EncodeDate(2017, 12, 3);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 5;
    FieldByName('FirstName').Value := 'Willetts';
    FieldByName('LastName').Value := 'Táng';
    FieldByName('Email').Value := 'awilletts1v@abbott.com';
    FieldByName('Company').Value := 'Abbott, Haley and Stiedemann';
    FieldByName('BooksRead').Value := 2;
    FieldByName('LastReport').Value := EncodeDate(2018, 6, 21);
    FieldByName('Created').Value := EncodeDate(2018, 1, 2);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 6;
    FieldByName('FirstName').Value := 'MacCaghan';
    FieldByName('LastName').Value := 'Ambrosio';
    FieldByName('Email').Value := 'amaccaghan27@cornell.edu';
    FieldByName('Company').Value := '';
    FieldByName('BooksRead').Value := 2;
    FieldByName('LastReport').Value := EncodeDate(2018, 10, 11);
    FieldByName('Created').Value := EncodeDate(2018, 1, 5);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 7;
    FieldByName('FirstName').Value := 'Burberye';
    FieldByName('LastName').Value := 'Naëlle';
    FieldByName('Email').Value := 'bburberye7@imgur.com';
    FieldByName('Company').Value := 'Quitzon, Legros and Swift';
    FieldByName('BooksRead').Value := 1;
    FieldByName('LastReport').Value := EncodeDate(2018, 5, 8);
    FieldByName('Created').Value := EncodeDate(2018, 1, 24);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 8;
    FieldByName('FirstName').Value := 'Birchenough';
    FieldByName('LastName').Value := 'Gaia';
    FieldByName('Email').Value := 'sbirchenough5@bravesites.com';
    FieldByName('Company').Value := '';
    FieldByName('BooksRead').Value := 2;
    FieldByName('LastReport').Value := EncodeDate(2018, 9, 27);
    FieldByName('Created').Value := EncodeDate(2018, 1, 30);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 9;
    FieldByName('FirstName').Value := 'Le Sieur';
    FieldByName('LastName').Value := 'Garçon';
    FieldByName('Email').Value := 'clesieur3@meetup.com';
    FieldByName('Company').Value := '';
    FieldByName('BooksRead').Value := 1;
    FieldByName('LastReport').Value := EncodeDate(2018, 5, 25);
    FieldByName('Created').Value := EncodeDate(2018, 3, 2);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 10;
    FieldByName('FirstName').Value := 'Hegge';
    FieldByName('LastName').Value := 'Eugénie';
    FieldByName('Email').Value := 'yhegge6@w3.org';
    FieldByName('Company').Value := '';
    FieldByName('BooksRead').Value := 1;
    FieldByName('LastReport').Value := EncodeDate(2018, 9, 11);
    FieldByName('Created').Value := EncodeDate(2018, 3, 4);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 11;
    FieldByName('FirstName').Value := 'Dansie';
    FieldByName('LastName').Value := 'Cléopatre';
    FieldByName('Email').Value := 'wdansie1l@bizjournals.com';
    FieldByName('Company').Value := '';
    FieldByName('BooksRead').Value := 5;
    FieldByName('LastReport').Value := EncodeDate(2018, 9, 7);
    FieldByName('Created').Value := EncodeDate(2018, 3, 10);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 13;
    FieldByName('FirstName').Value := 'Demko';
    FieldByName('LastName').Value := 'Karlik';
    FieldByName('Email').Value := 'kdemko5@carter-baumbach.com';
    FieldByName('Company').Value := 'Carter-Baumbach';
    FieldByName('BooksRead').Value := 1;
    FieldByName('LastReport').Value := EncodeDate(2018, 10, 9);
    FieldByName('Created').Value := EncodeDate(2018, 3, 18);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 16;
    FieldByName('FirstName').Value := 'Wallicker';
    FieldByName('LastName').Value := 'Rui';
    FieldByName('Email').Value := 'awallicker4@about.me';
    FieldByName('Company').Value := '';
    FieldByName('BooksRead').Value := 1;
    FieldByName('LastReport').Value := EncodeDate(2018, 8, 25);
    FieldByName('Created').Value := EncodeDate(2018, 4, 8);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 17;
    FieldByName('FirstName').Value := 'Damper';
    FieldByName('LastName').Value := 'Tori';
    FieldByName('Email').Value := 'tdampery@lowe.com';
    FieldByName('Company').Value := '';
    FieldByName('BooksRead').Value := 1;
    FieldByName('LastReport').Value := EncodeDate(2018, 9, 3);
    FieldByName('Created').Value := EncodeDate(2018, 5, 4);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 18;
    FieldByName('FirstName').Value := 'Sandeman';
    FieldByName('LastName').Value := 'Marten';
    FieldByName('Email').Value := 'asandeman1z@trellian.com';
    FieldByName('Company').Value := '';
    FieldByName('BooksRead').Value := 1;
    FieldByName('LastReport').Value := EncodeDate(2018, 7, 22);
    FieldByName('Created').Value := EncodeDate(2018, 5, 4);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 19;
    FieldByName('FirstName').Value := 'Pesak';
    FieldByName('LastName').Value := 'Gussi';
    FieldByName('Email').Value := 'gpesako@koepp.com';
    FieldByName('Company').Value := 'Koepp LLC';
    FieldByName('BooksRead').Value := 1;
    FieldByName('LastReport').Value := EncodeDate(2018, 8, 27);
    FieldByName('Created').Value := EncodeDate(2018, 5, 14);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 21;
    FieldByName('FirstName').Value := 'Oldknow';
    FieldByName('LastName').Value := 'Bondon';
    FieldByName('Email').Value := 'boldknow1g@gizmodo.com';
    FieldByName('Company').Value := '';
    FieldByName('BooksRead').Value := 1;
    FieldByName('LastReport').Value := EncodeDate(2018, 8, 26);
    FieldByName('Created').Value := EncodeDate(2018, 6, 7);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 22;
    FieldByName('FirstName').Value := 'Sorton';
    FieldByName('LastName').Value := 'Gib';
    FieldByName('Email').Value := 'gsorton1f@un.org';
    FieldByName('Company').Value := '';
    FieldByName('BooksRead').Value := 1;
    FieldByName('LastReport').Value := EncodeDate(2018, 8, 5);
    FieldByName('Created').Value := EncodeDate(2018, 6, 10);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 23;
    FieldByName('FirstName').Value := 'McKellar';
    FieldByName('LastName').Value := 'Göran';
    FieldByName('Email').Value := 'emckellaro@jenkinsparisian.com';
    FieldByName('Company').Value := 'Jenkins-Parisian';
    FieldByName('BooksRead').Value := 1;
    FieldByName('LastReport').Value := EncodeDate(2018, 8, 23);
    FieldByName('Created').Value := EncodeDate(2018, 6, 10);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 24;
    FieldByName('FirstName').Value := 'Gervasio';
    FieldByName('LastName').Value := 'Brancato';
    FieldByName('Email').Value := 'rervasio3419@email.it';
    FieldByName('Company').Value := 'Komerci';
    FieldByName('BooksRead').Value := 1;
    FieldByName('LastReport').Value := EncodeDate(2018, 8, 15) +
      EncodeTime(22, 12, 31, 0);
    FieldByName('Created').Value := EncodeDate(2019, 2, 16) +
      EncodeTime(22, 20, 16, 515);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 25;
    FieldByName('FirstName').Value := 'Rolando';
    FieldByName('LastName').Value := 'D''Ottavio';
    FieldByName('Email').Value := 'r.ottavio@alice.it';
    FieldByName('Company').Value := 'Motife Srl';
    FieldByName('BooksRead').Value := 1;
    FieldByName('LastReport').Value := EncodeDate(2018, 8, 23) +
      EncodeTime(12, 2, 17, 0);
    FieldByName('Created').Value := EncodeDate(2019, 2, 16) +
      EncodeTime(22, 20, 16, 516);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 26;
    FieldByName('FirstName').Value := 'Adolfo';
    FieldByName('LastName').Value := 'Alba';
    FieldByName('Email').Value := 'aa9876543@gmail.com';
    FieldByName('Company').Value := '';
    FieldByName('BooksRead').Value := 1;
    FieldByName('LastReport').Value := EncodeDate(2018, 9, 2) +
      EncodeTime(21, 55, 43, 0);
    FieldByName('Created').Value := EncodeDate(2019, 2, 16) +
      EncodeTime(22, 20, 16, 517);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 27;
    FieldByName('FirstName').Value := 'Pancrazio';
    FieldByName('LastName').Value := 'Muto';
    FieldByName('Email').Value := 'SuperPancrazio70@email.it';
    FieldByName('Company').Value := '';
    FieldByName('BooksRead').Value := 1;
    FieldByName('LastReport').Value := EncodeDate(2018, 9, 15) +
      EncodeTime(0, 32, 31, 0);
    FieldByName('Created').Value := EncodeDate(2019, 2, 16) +
      EncodeTime(22, 20, 16, 518);
    Post;
  end;
  with ds do
  begin
    Append;
    FieldByName('ReaderId').Value := 28;
    FieldByName('FirstName').Value := 'Owbridge';
    FieldByName('LastName').Value := 'Ian';
    FieldByName('Email').Value := 'iowbridge1v@joomla.org';
    FieldByName('Company').Value := '';
    FieldByName('BooksRead').Value := 1;
    FieldByName('LastReport').Value := EncodeDate(2018, 9, 28) +
      EncodeTime(1, 2, 21, 0);
    FieldByName('Created').Value := EncodeDate(2019, 2, 16) +
      EncodeTime(22, 20, 16, 519);
    Post;
  end;
{$ENDREGION}
  Result := ds;
end;

// -----------------------------------------------------------

function TReaderProxy.generateNewUniqueID: integer;
var
  NewID: integer;
begin
  // GenerateUniqueID: GetMax(ReaderId)+1 or 0 in there is no rows
  NewID := 0;
  Self.ForEach(
    procedure
    begin
      if ReaderId.Value > NewID then
        NewID := ReaderId.Value;
    end);
  Result := NewID;
end;

function TReaderProxy.LoacateReaderIdByEmil(const email: string): Variant;
begin
  if FDataSet.Locate('email', email, []) then
    Result := Self.ReaderId.Value
  else
    Result := System.Variants.Null()
end;

end.
